blog/urls.py
from django.urls import path
from blog import views
urlpatterns = [
    path('index/', views.blog_list, name='blog_list'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('type/<int:blog_type_pk>/', views.blog_type, name='blog_type')
]

comment/urls.py
from django.urls import path, include
from . import views
app_name = 'comment'
urlpatterns = [
    path('update_comment/', views.update_comment, name='update_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from ckeditor_uploader.fields import RichTextUploadingField
from read_num.models import ReadNum,GetReadNum
#博客类型的类
class BlogType(models.Model):
    type_name = models.CharField('博客类型', max_length=40)

    def __str__(self):
        return self.type_name
    class Meta:

        verbose_name='博客类型'
        verbose_name_plural=verbose_name

# 博客类
class Blog(models.Model,GetReadNum):

    title = models.CharField('标题', max_length=40)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    #内容字段
    content = RichTextUploadingField('内容')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creat_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='博客列表'
        verbose_name_plural = verbose_name
        ordering=['-creat_time']

blog/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from comment.models import Comment
from comment.form import CommentForm
from read_num.utils import read_num_method,get_seven_day_read_method
from read_num.models import ReadDetail
from .models import BlogType,Blog

# Create your views here.

def get_blog_list_comman_data(request,blog_all_list):
    paginator = Paginator(blog_all_list,5)
    page_num = request.GET.get('page', 1)
    # 获取所有页码
    page_of_blogs = paginator.get_page(page_num)
    #获取当前页
    current_page_num = page_of_blogs.number
    #获取前后两页的页码范围
    page_range = list(range(max(current_page_num-2,1),current_page_num))+\
                 list(range(current_page_num,min(current_page_num+2,paginator.num_pages+1)))
    #加上省略标记
    if page_range[0]-1>=2:
        page_range.insert(0,'...')
    if paginator.num_pages - page_range[-1] >=2:
        page_range.append('...')
    #加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0,1)
    if page_range[-1] !=paginator.num_pages :
        page_range.append(paginator.num_pages)
    blogtypes = BlogType.objects.all()
    context = {
        'blogs':page_of_blogs.object_list,
        'page_of_blogs':page_of_blogs,
        'page_range':page_range,
        "blogtypes" : blogtypes,
        # 'blog_types':BlogType.objects.annotate(blog_)

    }
    return context
def home(request):
    week,read_nums=get_seven_day_read_method(Blog)
    context={
        'week':week,
        'read_nums':read_nums
    }
    return render(request, 'home.html', context=context)

def blog_list(request):
    blogs=Blog.objects.all()
    context = get_blog_list_comman_data(request,blogs)
    return render(request, 'blog/blog_list.html', context=context)

def blog_type(request,blog_type_pk):
    blogtypes = BlogType.objects.all()
    blogs=Blog.objects.filter(blog_type_id=blog_type_pk)
    context = get_blog_list_comman_data(request,blogs)
    return render(request, 'blog/blog-type.html',context=context)


def blog_detail(request,pk):
    # 获取Blog对象
    blog=get_object_or_404(Blog,id=pk)
    #blog所有分类
    blogtypes = BlogType.objects.all()

    # 阅读计数cookie
    read_cookie_key = read_num_method(request,blog)
    # 评论对象
    blog_content_type = ContentType.objects.get_for_model(blog)
    comments =Comment.objects.filter(content_type=blog_content_type,object_id=blog.pk,parent=None)
    context={
        'blog':blog,
        'comments':comments,
        'comment_form':CommentForm(initial={'content_type':'Blog','object_id':blog.pk,
                                       'reply_to':0}),
        'blogtypes':blogtypes
    }
    response=render(request,'blog/blog_content.html',context=context)
    response.set_cookie(read_cookie_key,'true',expires=60*60*24)

    return  response

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}

    首页
    {% endblock %}</title>

    <!-- Bootstrap core CSS -->



    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'CSS/base.css' %}" rel="stylesheet">
{#    <link href="{% static 'CSS/111.css' %}" rel="stylesheet">#}
      {% block CSS %}
      {% endblock %}
  </head>

  <body style=" background-size: cover ">

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">MY BLOG</h3>
            <nav class="navbar navbar-default navbar-fixed-top" style="background-color:transparent ">
      <div class="container">
        <div class="navbar-header">

          <a class="navbar-brand" href="#" style="color: white">MY BLOG</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse" >
          <ul class="nav navbar-nav" style="color: white">
            <li><a href="{% url 'home' %}">首页</a></li>
            <li><a href="{% url 'blog_list' %}">博客列表</a></li>
            <li><a href="#"> 关于博主</a></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
               <li style="top: 15px;margin-right:10px ">欢迎登录</li>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="top:10px">
                    {{ user.username }} <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'logout' %}?from={{ request.get_full_path }}">退出 </a></li>
                    </ul>
                </div>
                {% else  %}
                    <li><a href="{% url 'login'%}?from={{ request.get_full_path }} ">登陆</a></li>
                    <li style="top: 15px"><span >or</span> </li>
                    <li><a href="{% url 'register'%}?from={{ request.get_full_path }}">注册</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
            </div>
          </div>
          {% block content %}

          {% endblock %}

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
 <script src="{% static 'bootstrap/jquery.js' %}"></script>

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  {% block extens_js %}

  {% endblock %}
  </body>
</html>

blog/templates/blog/blog-type.html
{% extends 'blog/blog_list.html' %}

blog/templates/blog/blog_content.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}
博客列表
{% endblock %}
{% block CSS %}
<script src ="{% static 'ckeditor/ckeditor-init.js' %}"> </script>
<script src ="{% static 'ckeditor/ckeditor/ckeditor.js' %}"> </script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    {% block blog_content %}
        <div class="col-sm-8 blog-main">
            <h1>{{ blog.title }}</h1>
            <h4>阅读 ({{ blog.get_read_num}})</h4>
            <h4>{{ blog.author }} {{ blog.creat_time }}</h4>
            {{ blog.content|safe }}
            {% if user.is_authenticated %}
            <form id="comment-form" class="comment-form" action="{% url 'comment:update_comment' %}" method="post">
                <p style="color: aquamarine">开始评论</p>
                {% csrf_token %}
                {% for form in comment_form %}
                {{ form }}
                {% endfor %}
                <br>
                <input class="btn pull-right btn-primary" type="submit"  value="评论" >
                 <span id="comment-error" class="text-danger pull-left"></span>
            </form>
        </div>
{% else %}

        <div class="col-sm-8 blog-main">
        <h5 class="pull-left">登陆之后方可评论，请登录或注册</h5>
            <br>
            <a class="btn btn-outline-success btn-danger pull-left" href="{% url 'register'%}?from={{ request.get_full_path }}">注册</a>
            <h4 class="pull-left">or</h4>
            <a class="btn btn-outline-success btn-primary pull-left" href="{% url 'login'%}?from={{ request.get_full_path }}">登录</a>
        </div>
        </div>
{% endif %}
        {% endblock %}
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
              <div class="sidebar-module sidebar-module-inset">
              </div>
              <div class="sidebar-module">
                <ol class="list-unstyled">
                </ol>
              </div>
              <div class="sidebar-module">
                <h4>博客分类</h4>
                <ol class="list-unstyled">
                    {% for blogtype in blogtypes %}
                    <li><a href="{% url 'blog_type' blogtype.pk %}">{{blogtype}}</a></li>
                    {% endfor %}
                </ol>
              </div>
        </div>

</div>
    <div id="comment-list">
    <h3>评论列表</h3>
    {% for comment in comments %}
      <div style="color: #2aabd2"> {{ user.username }} ({{ comment.comment_time|date:"Y-m-d H:i:s" }}):</div>
    <p>{{ comment|safe }}</p>
    {% empty %}
        暂无评论
    {% endfor %}
    </div>
{% endblock %}

{% block extens_js %}
    <script type="text/javascript">
    $("#comment-form").submit(function () {
         $("#comment-error").text('');
            if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }

            // 更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();

         $.ajax(
        {
            data: $(this).serialize(),
            url:'{% url 'comment:update_comment' %}',
            type:'POST',
            cache:false,
            success:function (data) {
                console.log(data);
                if (data['status'] === 'SUCCESS'){
                    var comment_html = '<div style="color: #2aabd2">' + data['username'] +
                                           ' (' + data['comment_time'] + ')：'  + '</div>'+
                                           data['text'];
                        $("#comment-list").prepend(comment_html);
                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                }

                else{
                console.log('没跳转');
            }

            }})
         return false;
    })



    </script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/blog_content.html' %}
{% block title %}
博客列表
{% endblock %}
{% block CSS %}
    <style>
    #title{
        font-size: 28px;
        padding: 0;
    }
    #theme{
        padding: 0;
        padding-left: 12px;
        font-size: 16px;
    }
    </style>
{% endblock %}
{% block blog_content %}
    <div class="col-sm-8 blog-main">

          {% for blog in blogs %}
              <div class="page-header">
                <p id="blog_title"><a id="title" class="btn btn-outline-success " href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></p>
              <p>主题<a id="theme" class="btn btn-outline-success btn-sm"  href="{% url 'blog_type' blog.blog_type.pk %}">{{ blog.blog_type.type_name }}</a> </p>
                <p id="author">作者：{{ blog.author }} 时间：{{ blog.creat_time|date:"Y-m-d H:i:s" }}  阅读：({{ blog.get_read_num }}) </p>
                <div id="content"> {{ blog.content|safe }}</div>
              </div>
          {% endfor %}

         <nav aria-label="Page navigation">
          <ul class="pagination">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
              {% for page in page_range %}
              <li><a href="?page={{ page }}">{{ page }}</a></li>
              {% endfor %}
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'CSS/index.css' %} ">

    <script src="{% static 'bootstrap/jquery.js' %}"></script>

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>

    <![endif]-->
  </head>
  <body>
  <div id="ima_header">

  </div>
    <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MY BLOG</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">


            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">首页</a></li>
                <li><a href="#">python</a></li>
                <li><a href="#">js</a></li>
                <li><a href="#">关于博主</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">MY BLOG</h1>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">

{#{% url 'blog_detail' blog.pk %}#}
          </div><!-- /.blog-post -->






    </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">

            <h2>分类</h2>

          <div class="sidebar-module">

            <ol class="list-unstyled">

            </ol>
          </div>

        </div>
        <!-- /.blog-sidebar -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </body>
</html>